<?php

namespace Epixa\UserBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * CredentialRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CredentialRepository extends EntityRepository
{
}